server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  pagehelper:
    helper-dialect: h2
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

  datasource:
    username: hsp
    password: 123456
    url: jdbc:h2:file:./userDB
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: exercise_HikariCP
      minimum-idle: 5  #最小空闲连接数量
      idle-timeout: 30000  #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 20  #连接池最大连接数，默认是10
      auto-commit: false  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000  #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000  #数据库连接超时时间,默认30秒，即30000


  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
      schema-locations: classpath:h2db/schema.sql
      data-locations: classpath:h2db/data.sql